services:
  ocr-react:
    image: justinfay501/ocr-react:${GIT_COMMIT_HASH-latest} # Image name
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ocr-react.rule=Host(`eremos.cloud`)"
      - "traefik.http.routers.ocr-react.entrypoints=websecure"
      - "traefik.http.routers.ocr-react.tls.certresolver=myresolver"
    deploy: # Rolling release (Blue Green Deployment)
      update_config:
        order: start-first
