services:
  ocr-react:
    image: justinfay501/ocr-react:latest # Image name
    ports:
      - "3000:3000"
    deploy: # Rolling release (Blue Green Deployment)
      update_config:
        order: start-first
