services:
  ocr-react:
    image: justinfay501/ocr-react:latest # Image name
    networks:
      - ocr-api_ocr_net
    ports:
      - "3000:3000"
    deploy: # Rolling release (Blue Green Deployment)
      update_config:
        order: start-first

# Network is defined in the backend stack
networks:
  ocr-api_ocr_net:
    external: true
